baseURL = "https://jmcarter17.github.io/famillecarter-blog/"
languageCode = "fr-ca"
title = "Les Super-Héros Carter"
theme = "ananke"

[pagination]
pagerSize = 10

[params]
description = "Un journal de famille"

[[menu.main]]
name = "À propos"
url = "/pages/a-propos-de-nous/"
weight = 20

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 30
